# Generated by Django 3.1.7 on 2021-04-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phoneNo', models.CharField(max_length=15)),
                ('isActive', models.BooleanField(default=False)),
                ('isBusy', models.BooleanField(default=False)),
                ('givenHourStart', models.DateTimeField()),
                ('givenHourEnd', models.DateTimeField()),
                ('realHourStart', models.DateTimeField(blank=True)),
                ('realHourEnd', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=45)),
                ('adress', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_pickup', models.DateTimeField()),
                ('adress_to', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(auto_now=True)),
                ('running_now', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.store')),
            ],
        ),
    ]
