# Generated by Django 3.1.7 on 2021-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=31.0, max_digits=7),
            preserve_default=False,
        ),
    ]
