# Generated by Django 3.1.7 on 2021-05-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20210504_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='realHourEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='realHourStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
